--liquibase formatted sql
--changeset multipledb:users_oracle_2  runOnChange:true

CREATE TABLE users_oracle_2
(
    id_y         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username_y   VARCHAR2(50) NOT NULL,
    first_name_y VARCHAR2(100),
    last_name_y  VARCHAR2(100)
);

INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('jconnor', 'John', 'Connor');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('sarahc', 'Sarah', 'Connor');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('mfox', 'Marty', 'McFly');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('evedge', 'Eve', 'Edgecombe');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('aripley', 'Ellen', 'Ripley');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('johnwick', 'John', 'Wick');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('laracroft', 'Lara', 'Croft');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('ethanh', 'Ethan', 'Hunt');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('nneo', 'Neo', 'Anderson');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('hpotter', 'Harry', 'Potter');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('ronweasley', 'Ron', 'Weasley');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('hermione', 'Hermione', 'Granger');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('dmorgan', 'Derek', 'Morgan');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('kline', 'Kiera', 'Line');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('mmaximus', 'Maximus', 'Decimus');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('rickgrimes', 'Rick', 'Grimes');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('bateman', 'Patrick', 'Bateman');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('selina', 'Selina', 'Kyle');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('gordonf', 'Frank', 'Gordon');
INSERT INTO users_oracle_2 (username_y, first_name_y, last_name_y) VALUES ('bwayne', 'Bruce', 'Wayne');

COMMIT;