--liquibase formatted sql
--changeset multipledb:users_oracle_1  runOnChange:true

CREATE TABLE users_oracle_1
(
    id_x         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username_x   VARCHAR2(50) NOT NULL,
    first_name_x VARCHAR2(100),
    last_name_x  VARCHAR2(100)
);

INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('jdoe', 'John', 'Doe');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('asmith', 'Alice', 'Smith');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('bking', 'Bob', 'King');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('clark', 'Clark', 'Kent');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('wwayne', 'Bruce', 'Wayne');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('pparker', 'Peter', 'Parker');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('dprince', 'Diana', 'Prince');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('tstark', 'Tony', 'Stark');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('srogers', 'Steve', 'Rogers');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('bnatasha', 'Natasha', 'Romanoff');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('bruceb', 'Bruce', 'Banner');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('thorodinson', 'Thor', 'Odinson');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('scottl', 'Scott', 'Lang');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('clintb', 'Clint', 'Barton');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('shazam', 'Billy', 'Batson');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('arthurc', 'Arthur', 'Curry');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('barrya', 'Barry', 'Allen');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('wallyw', 'Wally', 'West');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('victor', 'Victor', 'Stone');
INSERT INTO users_oracle_1 (username_x, first_name_x, last_name_x) VALUES ('kamalak', 'Kamala', 'Khan');

COMMIT;